// client/src/features/message-list/ui/DateSeparator/DateSeparator.tsx
import './style.scss'

import { IDateSeparatorProps } from 'src/features/message-list'

import { AppText } from 'src/shared/ui'

export const DateSeparator = ({ label }: IDateSeparatorProps) => {
  return (
    <div className="message-date-separator">
      <AppText size="small">{label}</AppText>
    </div>
  )
}

// client/src/pages/chat-room/ui/DateSeparator.vue
<script setup lang="ts">
import { AppText } from 'src/shared/ui'

import type { IDateSeparatorProps } from '../config/types'
const props = defineProps<IDateSeparatorProps>()
</script>

<template>
  <AppText :text="props.label" alignment="center" color="contrast-text" class="date-separator" />
</template>

<style lang="scss">
.date-separator {
  display: block;
}
</style>
