// legacy/legacy-client/src/pages/main/ui/Main/ChatRoom/ChatRoomMessages/DateSeparator/DateSeparator.tsx
import { AppText } from 'src/shared/ui'

import styles from './DateSeparator.module.scss'
import { IDateSeparatorProps } from './types'

export const DateSeparator = ({ label }: IDateSeparatorProps) => {
  return (
    <div className={styles.root}>
      <AppText size="small">{label}</AppText>
    </div>
  )
}

// client/src/pages/chat-room/ui/DateSeparator.vue
<script setup lang="ts">
import { AppText } from 'src/shared/ui'

import type { IDateSeparatorProps } from '../config/types'
const props = defineProps<IDateSeparatorProps>()
</script>

<template>
  <AppText :text="props.label" alignment="center" color="contrast-text" class="date-separator" />
</template>

<style lang="scss">
.date-separator {
  display: block;
}
</style>
