// client/src/shared/ui/AppHeader/AppHeader.tsx
import './style.scss'
import { createElement } from 'react'

import { createClassNameWithModifiers } from 'src/shared/lib'

export const AppHeader = ({
  tag = 'h3',
  children,
  additionalClassName,
  accent = false,
  bold = true
}: {
  tag?: 'h2' | 'h3' | 'h4'
  children?: React.ReactNode
  additionalClassName?: string
  accent?: boolean
  bold?: boolean
}) => {
  const className = createClassNameWithModifiers({
    rootClass: 'app-header',
    modifiers: [accent && 'accent', bold && 'bold'],
    additionalClassName
  })

  return createElement(tag, { className }, children)
}

// client/src/shared/ui/AppHeader/AppHeader.vue
<script setup lang="ts">
import { computed } from 'vue'

import { createClassNameWithModifiers } from 'src/shared/lib'

import { APP_HEADER_DEFAULT_PROPS } from './constants'
import type { IAppHeaderProps } from './types'

const props = withDefaults(defineProps<IAppHeaderProps>(), APP_HEADER_DEFAULT_PROPS)

const className = computed(() =>
  createClassNameWithModifiers({
    rootClass: 'app-header',
    modifiers: [props.accent && 'accent', props.bold && 'bold']
  })
)
</script>

<template>
  <component :is="props.tag" :class="className">
    <slot />
  </component>
</template>

<style scoped>
h2.app-header {
  font-size: 24px;
}

h3.app-header {
  font-size: 20px;
}

h4.app-header {
  font-size: 18px;
}

.app-header {
  margin-top: 0;
  margin-bottom: 0;
  color: var(--p-app-text-muted);
}

.app-header--bold {
  font-weight: bold;
}

.app-header--accent {
  color: var(--p-primary-color);
}
</style>
